### ISSUE TITLE
Unable to do first-offs, and enter non-cons and shortfalls on Chromebooks in tablet mode

### ISSUE THREAD

**Issue by AlexLT1** [commutron/neptune-dev#8] opened 2021-05-10 20:42 UTC
As explained in title. They do not display while in tablet mode, however instantly pop back up once you unfold it back into laptop mode. Edit: it displays if you change the display to full screen before you fold it, but this does make it a pain to navigate around on the laptops

**Comment by mattandwhatnot** [comment] 2021-05-11 04:59
The bottom form bar may be offscreen but I cannot reproduce this condition. Please supply screenshots and the display resolution.
Is this occur on the old 10" Asus as well as the new laptops? (HPs? Lenovos? I can't remember)

also if you are going to post issues without logging into Github, please include your name so I can follow up properly.

**Comment by 1324692893** [comment] 2021-05-11 13:06
They are hp laptops, they are about 10-14 inches but that's a rough guess. We changed the resolution to the highest, and lowest.

Additionally I tried to change my account username last night to no success. I will continue to tag my name at the bottom of each comment. I'll check to see why I wasn't given that option and it should be fixed for next time. 

-Alex

**Comment by mattandwhatnot** [comment] 2021-05-13 02:15
Your going to need to be more specific.
Is it a problem on the Asus C101?
What is the HP display resolution?
Is the bar completely or partially obstructed?
If you switch to Explore, is the bottom toolbar missing?

**Comment by AlexLT1** [comment] 2021-05-13 13:34
Issue present on both hp and asus chromebooks

Hp display resolution is 1518 x 853
Asus display resolution is 1422 x 889

Changing resolutions on either does not affect the bar at the bottom going away

When switching to explore, the bottom toolbar with the options to print labels, delete, etc, also becomes obstructed.

**Comment by mattandwhatnot** [comment] 2021-05-13 19:29
As a temporary work around, try setting the flag
(chrome://flags) "force ui mode" to "clamshell".

**Comment by AlexLT1** [comment] 2021-05-13 20:42
Force ui mode has since been removed from the flags. Neither in available or unavailable flags. Cannot try this to see if it will work for the time being

**Comment by mattandwhatnot** [comment] 2021-05-14 03:52
The problem is how "mobile" UIs measure vh units and the whole layout is built around vh units. Can be mitigated with a somewhat time consuming refactor. 

I feel like we're getting sidetracked but for clarifications sake, the resolution isn't going to affect the issue but it's helpful for testing. I'm pretty sure the possible native resolution of the HP 14 is either 1366 x 768 or 1920 x 1080. 
_Are you going to be consistently running them at 1518 x 853 ?_ 
The little Asus C101 is definitely 1200 x 800. 
Monitors are 1600 x 900, 1920 x 1080 or Adam's 2560 x 1440.
I'm pretty sure the old 15" Lenovos are 1366 x 768.
_What Asus is 1422 x 889 ?_

**Comment by AlexLT1** [comment] 2021-05-14 16:46
Sorry I did not check if they were the native sizes. I left them where they were at and scrolled to the other side just to see if things would work. The native display sizes are


1366 x 768 hp

1280 x 800 asus

**Closed** 2021-05-25 16:23 UTC
